name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    # We specify frontend because all your code and package.json are in the frontend folder
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build the Project
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --project gethsemanechoir-7f162 --non-interactive
        env:
          # This token comes from your GitHub Secrets
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
